### PR TITLE
Resize the avatar on plain repost without comment

### PR DESCRIPTION
**Pull request by dtonon**
Apply the logic to highlight the original poster if the repost is without comment.
It's not pixel perfect, the top bar and the bottom icons require a full revision but it's a step on the right direction.

Screenshot 2023-03-01 alle 13 23 22

### CODE REVIEW

**Comment by dtonon** [comment]
Wait to merge, there is a problem with the check of empty content.

**Comment by dtonon** [comment]
Fixed with an hack. Because EventKind::Repost is both kind 6 and kind 1 + mention to verify if is the first one I check if the content could be a JSON by the { ... } structure:

```rust
let re = Regex::new(r"^\{.*\}$").unwrap();
re.is_match(&event.content)
```
Is there a way to access to the original kind number?

**Comment by mikedilger** [comment]
Later in the code we look at the content and try to json_decode it into an Event. That event will have the original kind number. That process will also be more certain about the content than the Regex would be.  But it's done further down.  So maybe that code needs to be moved up before rendering the avatar so you can make decisions based on it's results.

**Comment by dtonon** [comment]
@mikedilger why checking the event id if we know that kind 6 have to include the full event payload?
The problem here, if I'm not wrong, is that a kind 1 event is classified as EventKind::Repost while in [event_kind.rs](https://github.com/mikedilger/nostr-types/blob/master/src/types/event_kind.rs) the matching seems strictly related to the raw kind.

Repost NIP (kind 6) has been archived, the "Mentions" currently are just a kind 1 without any spec that differentiate plain repost (the content is only the note that refer to a e-tag), a quote (text + e-tag) and a mention (one or more e-tag inside the text).

Perhaps we should add "virtuals" EventKind::Quote and EventKind::Mention, until the specs are polished. But a database level I would always save the raw kind id, to do a migration if needed.

**Comment by mikedilger** [comment]
I think nostr-types should represent what the event says, if it is 6 it is Repost if it is 1 it is TextNote.  We can render however we want, so if we have a TextNote with a mention and empty body or whatever the rule is, we can render it like a repost.

**Comment by mikedilger** [comment]
> I don't know the better way to render this case (perhaps fetch the note and show it like the full kind-6)

I always intended to do that. They should look the same. But maybe rendering it like a kind-1 mention.

And maybe we should wait, because numerous people are shredding NIP-10 into lots of different opinions and who knows where that will end up.

**Pull request merged**
