### PR TITLE
relay lists: restyle option drop down

### PR DESCRIPTION
**Pull request by bu5hm4nn**

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
@dtonon I needed to create a new style to work on the accent background. You can fine-tune in the theme in a function called `get_on_accent_style()`. Right now it gets the style for the opposite mode (dark->light) and then modifies it a bit. I did the modification for light mode, dark mode is still missing.
Screenshot 2023-09-06 at 17 35 43

**Comment by dtonon** [comment]
@bu5hm4nn really nice, I will check it!

**Comment by bu5hm4nn** [comment]
@dtonon I just merged unstable in again to bring this branch up to date. We still need styling for dark mode, so any hints from you on that would be appreciated.

**Comment by dtonon** [comment]
A quick feedback:

* We should try to don't touch the right border with the popover.
* Apply the same corner radius used in the rows
* For the text color use the same color of the rows (white / dark gray)
* On the hover just increase 10% the brightness

These should work for both themes in a decent way.
We will full review the dark one.

**Comment by bu5hm4nn** [comment]
@dtonon See if you like it this way. If you look at the commit you can see where the x-position of the dropdown can be adjusted.

**Comment by bu5hm4nn** [comment]
@dtonon this is still awaiting your review

**Comment by dtonon** [comment]
@bu5hm4nn sorry I missed this.
I just pushed a review on spacing and colors, including the dark theme (it's not perfect but for now it is ok).

**Review by dtonon — APPROVED** [review]

**Pull request merged**
