### PR TITLE
Features/improve search ux

### PR DESCRIPTION
**Pull request by dtonon**
See the commit messages for more info

### CODE REVIEW

**Comment by dtonon** [comment]
[8170676](https://github.com/mikedilger/gossip/pull/288/commits/817067621cf88d88df2ef1d7485e30d662757462) is a dirty teak: should be more correct to focus the first time the section is redered, otherwise I cannot anymore use tab move around, but I don' know the correct way to achieve this. In egui is there a way to differentiate the first rendering ("widget mounted" phase) and the next rendering refresh?

**Comment by mikedilger** [comment]
You could add a bool to GossipUi that is set whenever the Search page is selected (ui/mod.rs line 303 in function set_page()), and on the search page update function if that flag is set, you focus the input box and clear the flag.

**Comment by dtonon** [comment]
Updated as you suggested.

Note: after master rebase and locally it gives me this error:

>   Running `target/debug/gossip`
 INFO src/db/mod.rs:123: Upgrading database to version 28
Error: Sql(SqlInputError { error: Error { code: Unknown, extended_code: 1 }, msg: "table event_flags already exists", sql: "CREATE TABLE event_flags (\n  event TEXT PRIMARY KEY NOT NULL,\n  viewed INTEGER NOT NULL DEFAULT 0,\n  CONSTRAINT fk_event FOREIGN KEY (event) REFERENCES event (id) ON DELETE CASCADE\n);\n\nRENAME TABLE event_seen TO event_relay;\n", offset: 13 })

I commented it to test the update.

**Comment by mikedilger** [comment]
I fucked up my rebase aparently.  Pull, but then you need to manually do 1 of 2 options: 1) delete event_flags and try again, or 2) increment your schema version in local_settings

The second option is "UPDATE local_settings SET schema_version=28"

You do this in sqlite.  You need the path to your database (on Help>About page).  You need to install sqlite3.
Then you run
$ sqlite3 PATH

Then at the prompt do the "UPDATE local_settings SET schema_version=28"

Then ".quit" <RETURN>

**Comment by dtonon** [comment]
Thanks, I was just tweaking the schema versions to try to solve this out. Done.

**Pull request merged**
