### PR TITLE
Move "Coverage" to it's own view

### PR DESCRIPTION
**Pull request by bu5hm4nn**
@dtonon please review

### CODE REVIEW

**Comment by dtonon** [comment]
It's ok for me.
What do you think if we keep this PR to also update the design?
I would use the same white rows style used in the relays view.

**Comment by bu5hm4nn** [comment]
Changed to "draft" to update row style

**Comment by dtonon** [comment]
@bu5hm4nn I extracted this form the relays mockups.
Could you try to add the button on the top right? Seems a nice place (we will need to tweak the height of select/search/buttons later).

@mikedilger what infos do you think we need to highlight in this view?

Screenshot 2023-08-25 alle 12 05 26

This is what I see now on unstable:

image

What exactly means "coverage short by 1 relay(s)" ?
It seem to list users that have less than 4 relays and so with a low coverage.

Because the are name would make sense to list all the users and the add a select to filter all/low coverage?
This way adding a filter per relay we can know who use a relay, and link this view to the details relay view:

image

If this is ok I need a way to list all the relays below the user name.

Last: the "Pick relays" button currently acts only on the listed users or on all the followed?
If we show the full list, filterable, we this button should work only on the visibile users (that can also be the output of a filter/search).

**Comment by mikedilger** [comment]
You could use relay_assignments_iter() on the gossip relay picker, and then juggle the data around.  It comes in the form:

```
relayurl -> [pubkey, pubkey, pubkey]
```

And you want

```
pubkey -> [relayurl, relayurl, relayurl]
````

Which is not stored anywhere so you have to create it.

> Last: the "Pick relays" button currently acts only on the listed users or on all the followed? If we show the full list, filterable, we this button should work only on the visibile users (that can also be the output of a filter/search).

"Pick Again" does not have parameters. It tries to find ANY relay that will improve the coverage of ANY person who is not at full coverage already.  But it is useless at this point because the code already loops until it can't find anymore.  I think there are only rare edge cases where a relay was in the "sin bin" and has come out of it, or was manually disconnected, and it hasn't been "picked" again yet because nothing triggered the picking code yet.

That button is an advanced rarely-used thing.  Style it as such.

**Comment by bu5hm4nn** [comment]
@dtonon I think what you are doing in that mockup belongs on the "People" page instead. It already has a list of relays for each followed person. We could work on restyling that at some point.

The current coverage report really is info about what the relay picker came up with. While I'm sure @mikedilger uses it all the time to see how the picker is doing, I think it is a very low frequency view for most users. I would humbly suggest not giving it it's own menu entry but making it a sub-page of "Active". See screenshot below:
Screenshot 2023-08-25 at 12 03 37

**Comment by dtonon** [comment]
@bu5hm4nn you are absolutely right, my fault. In my [figma mockup](https://www.figma.com/file/FdDxNZE35f1I8duunMOQkZ/Gossip---Relay?type=design&node-id=2%3A391&mode=design&t=cR7NI4Z5ZtPNcTGu-1) I was speculating how to merge people and coverage, but now that I understood better the coverage logic I definitively agree that this view can be safely linked in a not priority spot.

I would suggest to move the link in the top-right popover menù and call it "Low coverage report".
In the same popover we can add the "Pick again" button, that is a low frequency tool, as stated by @mikedilger.

image

And this could be the final coverage page.
I would like to see the relays here too, so I can evaluate how actually severe the low coverage is.

image

Clicking the row should bring to the profile page.

**Comment by bu5hm4nn** [comment]
@dtonon Please review the branch.

If I would remove the "Go to profile of xxx" on-hover-text for the entire entry then the on-hover text for the copy button would work. Do you know of a better unicode copy symbol? the "next page" symbol did not work (missing from our fonts somehow).

Should be pretty much there except for the npub length. I'm not sure if we have some npub shortening code somewhere already, I didn't have time to look right now.

**Comment by dtonon** [comment]
@bu5hm4nn 

> If I would remove the "Go to profile of xxx" on-hover-text

Yes 👍

> Do you know of a better unicode copy symbol?

The current one is ok! Let's use these standard chars for now, eventually we will review all the icons using custom SVG.

> Should be pretty much there except for the npub length.

PR: https://github.com/bu5hm4nn/gossip/pull/1
Just to take confidence with rust again, feel free to trash it :)

## Design notes

- [ ] The hover effect is definitively needed in this sort of lists, but I would like to keep the row white in the default state to increase the readability (like in the main feed). I would remove the hover until we will review it everywhere in a coherent way; otherwise, we are going to scatter different UI/UXs around and later will be a pain to fix them. So let's simply make the rows white, the cursor-pointer is enough for now;
- [ ] I would show only the relays' host, without the protocol and the final slash;
- [ ] Padding between elements inside the row should not be larger than the inner row padding (general rule, I will develop some guidelines about this that we can formalize in the components);
- [ ]  I would add a quick button on the top right to go back to the monitor. Different colors for the two buttons helps to highlight them and defines a priority;

image

- [ ] At the bottom of the list we should add a space equal to the row's height itself (general rule);

## Technical notes

- [ ] The setting is "less than 2 relays", so I correctly see only 1 relay below the user name, but if I click it I often/always see ~ > 3 relays;

image

**Comment by bu5hm4nn** [comment]
How about a "back to activity monitor" link instead of the button?
(all links next to a .heading() are TOP aligned right now, which I need to fix once)

Screenshot 2023-09-01 at 17 18 40

**Comment by bu5hm4nn** [comment]
@dtonon Please review again. 

I don't know if we should remove the wss or ws portion as that could be interesting information about the relay, but I implemented it anyways.

**Comment by dtonon** [comment]
@bu5hm4nn 

> Please review again.

Checklist updated.

> How about a "back to activity monitor" link instead of the button?

I would avoid to put a "link" here, too many different elements, and it is complex to manage a responsive behaviour when the window is resized, ex:

image

The two buttons right aligned in this case should stay in a row below the page title.
Alternatively, we could add the "link" above the title, left aligned (it is a typical web format), but we don't have any other view with this format, so I would stick with the two buttons.

> I don't know if we should remove the wss or ws portion as that could be interesting information about the relay, but I implemented it anyways.

The main information here is the number of relay, the list is a plus I added to be a little more informative, but I don't think the user could be really interested about the protocol in this context.

**Comment by dtonon** [comment]
@bu5hm4nn if adding the buttons to the popover is a long task, we can move them to a row above:

image

Same for the "Coverage report".
It is not the best solution, of course; but it is ordered, clean and scalable, if we need to add more buttons short-term.
We will consolidate into a standard structure as soon as we review all the interfaces.

**Comment by bu5hm4nn** [comment]
@dtonon I think this is done from my side

**Comment by dtonon** [comment]
@bu5hm4nn good!

I only still have the [problem](https://github.com/mikedilger/gossip/pull/478#issuecomment-1700721211) related to relay showed:

> The setting is "less than 2 relays", so I correctly see only 1 relay below the user name, but if I click it I often/always see ~ > 3 relays;

As said [yesterday](https://github.com/mikedilger/gossip/pull/478#issuecomment-1704395615), can we transform the  "Coverage report" link in a button too? Otherwise I would move it back to the side menu, it is a more cleaner solution that have it near the title.

**Comment by bu5hm4nn** [comment]
@dtonon I changed it to a button. I left the location so that the filter and search region stays the same in all relay views.

**Comment by dtonon** [comment]
@bu5hm4nn ok! Is it possibile to right align all the inputs, included the search one?

**Comment by bu5hm4nn** [comment]
@dtonon done

**Comment by dtonon** [comment]
@bu5hm4nn I still see the "Coverage Report" left aligned, I meant to right align this one too :)

**Comment by dtonon** [comment]
@bu5hm4nn thanks 👍

**Comment by bu5hm4nn** [comment]
@dtonon can we merge this one? The issue with how many relays you see vs the setting is not related to the UI

**Comment by dtonon** [comment]
@bu5hm4nn about the UI the only glitches I still se are the text (reasons) that sometime overlap other elements:

image

And the Coverage / Pick again buttons that should be darker with a white/light font.

But maybe these are two things that we can review later, checking the whole app and start thinking about a components set?

**Comment by mikedilger** [comment]
Master doesn't need perfection it just needs forward progress.  I've merged this branch in.

**Pull request closed without merging**
