### PR TITLE
Extract theme related functions

### PR DESCRIPTION
**Pull request by bu5hm4nn**
In order to facilitate the creation of different display themes, I moved the code previously contained in style.rs into a new mod called 'theme'. The idea is to
- let users choose a theme in settings
- each theme should still support a dark and a light mode
- create a `trait Theme` that new themes shall implement
- give each theme it's own file, so that future changes to a theme will only affect a single file

I purposely did not refactor how styles are accessed yet (using trait Theme we can make it a bit more structured), as I wanted to gather feedback on this approach first. 

Also I am very new to Rust (after 15 years C++), so please correct me if something can be done better in this language.

Is this kind of work desired or should I just stay forked and create my own look?

### CODE REVIEW

**Comment by mikedilger** [comment]
I was planning on doing this. I was intending to supply dark and light variants of 2 or 3 color schemes, but well defined, not letting users choose each little detail or even color hues, just the theme itself.

This kind of work is very welcome.

I haven't looked at this code yet, I'm just responding to your comment.

**Comment by mikedilger** [comment]
I like this idea where each theme has it's own dark and light variant even better.

I do think we should perhaps refactor the trait next as you suggest.  I'm going to leave it up to you since you're on a roll here.   I can either merge now or later (but right now I have to leave the office and go home).

**Comment by bu5hm4nn** [comment]
The basic trait `trait Theme` is already extracted in `src/ui/theme/mod.rs`. When you have time for a review I think it would be good to merge early and often and do baby changes so we don't end up in merge hell.

**Comment by bu5hm4nn** [comment]
I pushed one more change where I moved the feed frame styling into the theme trait to show how it could be done. Sadly `egui::Frame` does not seem to expose a single 'style' struct. Of course mod theme should hold a global copy of the current theme and not create new objects every time. It should also remember the dark_mode setting and expose functions for the settings module.

**Comment by mikedilger** [comment]
I'd like to introduce you to 'cargo clippy' and 'cargo fmt'.  I tend to run these before pushing anything.  This time I will do it because I want to merge this stuff now.

**Comment by mikedilger** [comment]
And BTW I am now using the Roundy theme

**Comment by bu5hm4nn** [comment]
Thanks for merging! Of course I will check out clippy and fmt, like I said, I'm brand new to Rust.

**Comment by mikedilger** [comment]
and already quite adept at it.

**Pull request merged**
