### PR TITLE
Restructure note rendering to support nested reposts

### PR DESCRIPTION
**Pull request by bu5hm4nn**
Should support design as laid out in #305

### CODE REVIEW

**Comment by mikedilger** [comment]
Because this was so many commits, I squash merged it on a test branch so I could read the final difference instead of so many little separate incomplete changes.  I will do a regular merge after reviewing it.  I haven't finished reviewing it.

I don't like the renaming of 'as_reply_to' which is the flag indicating this is the note above the post area.  Yes, maybe it's only current effect is that it hides the footer, but by making this rename we lock ourselves out of easily understanding what it means and being able to do other things with that particular special post.  Don't change them all back: In note/mod.rs line 371 or so you can create a variable called 'hide_footer' like this:
````
let hide_footer = if as_reply_ to {
    true
} else if parent_repost.is_none() {
   ...
````

Also run `cargo fmt` and commit those changes as "cargo fmt".

I'll continue reviewing later.

**Comment by mikedilger** [comment]
One more thing, I was using this commit and I didn't see any indented reposts anywhere, no shrunk avatars, all I saw were links.  Was that the goal, or did I simply not encounter the reposts you are restyling?

**Comment by bu5hm4nn** [comment]
> I don't like the renaming of 'as_reply_to' ...
I changed it back in the outer code as requested, where there is no other meaning to the variable. However on `render_note_inner()` we now have more than one reason to hide the footer (we also hide the footer of the reposting post as discussed in issue #305) so I left it at `hide_footer` there.

**Comment by bu5hm4nn** [comment]
> One more thing, I was using this commit and I didn't see any indented reposts anywhere ...

Something must have gone wrong on your squash. This is how a repost looks in 'Default' Theme:
Screenshot 2023-03-21 at 23 36 38

And this is in classic theme (after a restart to revert to square avatars)
Screenshot 2023-03-21 at 23 47 22

**Comment by bu5hm4nn** [comment]
If you're seeing only a link then most likely it's because `GLOBALS.events.get(id)` on `src/ui/feed/note/mod.rs` line 83 did not return an event (what I call 'not in the cache').

**Pull request merged**
