### PR TITLE
Feature/style dm chats

### PR DESCRIPTION
**Pull request by bu5hm4nn**
Design discussion: #483

### CODE REVIEW

**Comment by dtonon** [comment]
@bu5hm4nn seems good!

But there is a strange problem, the list flickers and every few seconds it goes blank and there is just an "ERROR" in the upper left corner. Have you experienced something similar?

Multiline messages are shown like this, with more lines.
I would keep max 2 lines for every preview.

image<br/>

We need to add the pointer cursor to make it clear that the row is clickable.
(we will think an app wide hover interaction later)

In the specific chat I would use just the user's name as title, without the "Private Chat with" prefix.
And I would make it the same size of the other title, so bigger.

**Comment by mikedilger** [comment]
DM chat was saying ERROR if you had not unlocked your keys.  Because when you needed me to include the text of the last message in the channel, that needs your private key, so DmChannelData was not being returned when you first startup, Error was.  I changed it to a simple message.

**Comment by dtonon** [comment]
The error message before the unlock is clear, to me it is happening after, too. The view flickers and shows the error every few seconds. I will record a video.

Btw when locked I would simply hide the private chats item in the menu.

**Comment by bu5hm4nn** [comment]
@dtonon Please give this branch another try now. See commits above (I made one commit per issue addressed so it's clear what was done).

**Comment by dtonon** [comment]
@bu5hm4nn 

No more flickering and "errors" message, but the scrolling is really slow, and I cannot stop it, has a long inertia.

The text preview is a bit weird:

image

Is it not possible to define a text area with a width of 80% of the row, load a longer text, and let the container cut it?

image

Other important thing: the row background should be in the `panel_fill` color (so white for the light theme and dark gray for the dark one).

**Comment by bu5hm4nn** [comment]
@mikedilger This is now ready to merge

**Comment by dtonon** [comment]
@bu5hm4nn I still have the lag problem, where you able to reproduce it?

**Comment by bu5hm4nn** [comment]
I was able to reproduce it and it seems to be because we query the entire db on every UI refresh. So I think we need to cache the DM list just as we do with the feeds.

**Comment by mikedilger** [comment]
Is the lag problem worse with this PR, or no different?  If it's the same, I'll merge.  Otherwise I'll fix that lag problem first.

**Comment by mikedilger** [comment]
Ok I fixed the lag problem on unstable.

**Pull request merged**
