### PR TITLE
Feature/tagging

### PR DESCRIPTION
**Pull request by bu5hm4nn**

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
@mikedilger I went straight for 4. because that sounded like the hardest thing. I hit a bit of a wall adjusting the cursor to the new length. I wish there was an override function for inserting text as well so we could re-map the position. The following clip shows the problem, as soon as you hit space, it inserts the space in the underlying string, and you can't advance after the nurl because the ccursor follows the displayed galley.

https://github.com/mikedilger/gossip/assets/3328670/adbe5b8b-3d19-47ac-afcf-a6871c82b6ec

**Comment by bu5hm4nn** [comment]
I pushed the above to a new branch on my repo https://github.com/bu5hm4nn/gossip/tree/feature/tagging-modifying-highlighter

**Comment by bu5hm4nn** [comment]
@dtonon Please give this another look. A lot has improved in the tagging UI.

**Comment by bu5hm4nn** [comment]
I've added a button that does a "raw" content preview. I think it would be really nice to also have the option to see the final JSON before sending. I think that would be a power-feature worth having. (As I think gossip appeals to the power users)

**Comment by dtonon** [comment]
@bu5hm4nn it works very well!

Minor glitches:

- If the user fully type the name and then press a space to continue the sentence, the "@" is not removed.

- If the user user the left arrow to move when the popups open, the search is refreshed using the string between the @ and the cursor; I think it should keep using the full string. Example:

image
<br/><br/>
I published some designs and interactions note here: https://github.com/mikedilger/gossip/issues/566

**Comment by bu5hm4nn** [comment]
Thanks @dtonon. I agree that it would be nice to always search for the full term. I will try to do that. 

- [ ] always search with full word following '@', as long as the cursor is somewhere in the word
- [ ] support <SPACE> as a completion key
- [ ] add 'following status indicator' to profile hover

**Comment by mikedilger** [comment]
I like what I see (I haven't looked at the code, but I used it) and would merge it, but I presume based on the #566 there is more to do so I'll wait for that to resolve. Just let me know when you think this should be merged.

**Comment by mikedilger** [comment]
> At this point I would remove the "@" from the general notes rendering. Do you agree @mikedilger?

I don't have much of an opinion on it.

**Pull request merged**
