### PR TITLE
Pending and Notifications

### PR DESCRIPTION
**Pull request by bu5hm4nn**

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
@mikedilger I need your review on lib/pending.rs in this branch. There might be a few opportunities for rust optimizations in there.

**Comment by dtonon** [comment]
@bu5hm4nn great progress!

It's really nice we can sometimes include in the row a "solving button"; I would just use a button for the "Manage" (generic) action.

I agree that is better to use the "Day Month Year" format for the dates.

Did you moved the Auth/Connection on the colored label, to have more space for the relay?

Updated design:

image
<br/><br/>

A minor bug: if I set the remember toggle for more relay connections, when I approve/deny one, the other toggles are reset.

**Comment by bu5hm4nn** [comment]
> Did you moved the Auth/Connection on the colored label, to have more space for the relay?

I moved it because to me that word is in the middle of nowhere and it's not really clear what it means. Putting it in the colored label to me at least is very clear.

> I agree that is better to use the "Day Month Year" format for the dates.

I would like to use the OS setttings for the date format but I haven't found a way to get that yet.

**Comment by mikedilger** [comment]
I pushed a branch feature/pending-notifications with some improvements.  Is there anything in particular that you are worried about? I didn't review it tightly.

**Comment by bu5hm4nn** [comment]
Screenshot 2024-03-28 at 22 37 22
@dtonon please review the icon area

**Comment by bu5hm4nn** [comment]
- [ ] persist "Remember" settings across re-calc of notifications
- [ ] truncate labels for "pending.rs" type notifications
- [ ] make notifications fit with minimum window size

**Comment by dtonon** [comment]
@bu5hm4nn 

> I moved it because to me that word is in the middle of nowhere and it's not really clear what it means. Putting it in the colored label to me at least is very clear.

I grasp the the position can be tricky, but has its logic. The colored label should just carry the information about the row type (relay request), it has a smaller font and the user with habit will see only the color of it; every other info should be in the main row space, so one can visually read "xxxx.com request a Auth/Connectin and I can Approve/Decline it".
I don't know if it is possibile with egui, but I would give a fixed size to every column except the first one with the name of the relay.

**Comment by bu5hm4nn** [comment]
Screenshot 2024-03-29 at 13 08 51
Screenshot 2024-03-29 at 13 09 15

**Comment by bu5hm4nn** [comment]
@dtonon I tried to make it read like a sentence, however to me authenticate and connect don't look different. Can we use another color for authenticate? To me it is much different as authenticating proves this client has the private key and IS ME, otherwise it could also be someone else subscribing to me.

Also we need to make NIP46 request very prominent since they are time critical (if any of the clients goes offline while the request is open it will not work because they are ephemeral). I would suggest using the `L 0` area for NIP46 as we don't have any "log items" right now.

**Comment by bu5hm4nn** [comment]
Screenshot 2024-03-29 at 18 40 39

**Comment by mikedilger** [comment]
I merged this locally and I don't see anything.  One of my lists is out of sync so I should see something.

**Comment by mikedilger** [comment]
First, it doesn't respect dark mode. It is far too bright for me in dark mode.

Second, can we make it subdued if you have nothing pending?  It's not obvious to notice a '3' versus a '0' it should change colors or something to indicate visually that something needs to be addressed.

Third, fix spelling of 'localy'

Fourth, I have a patch for relay list comparison which I will submit soon to the branch on github.

**Comment by mikedilger** [comment]
There is a problem with the Followed list sync, because we have private entries that cannot be synced.  I will patch that soon too.

**Comment by bu5hm4nn** [comment]
> it should change colors or something

I agree and I also wish we had an icon or something, the letter + number doesn't appeal to me right now

**Comment by dtonon** [comment]
@bu5hm4nn

> Normal view with NIP46 request

In my design this sort of situation when there is a payload to inspect, is managed via the "view details" button; this should open a modal with a scrollable text area, and below the buttons (Rember) - Accept - Decline

> I tried to make it read like a sentence, however to me authenticate and connect don't look different.

The idea is interesting, but unfortunately the sentence makes the individual elements more difficult to read.
My design should solve this putting the Connection / Auth on a specific "column", the space around highlight the connection. Is it not (easily) doable?

We need to add also the reasons? The list can be quite long...

> Can we use another color for authenticate?

I would gladly avoid that, otherwise we need to extend the palette and manage a light/dark sync.

> To me it is much different as authenticating proves this client has the private key and IS ME, otherwise it could also be someone else subscribing to me.

I definitively agree that we should emphasize the authorization as much as possible.
Maybe adding an icon:

image

**Comment by dtonon** [comment]
@bu5hm4nn we have a problem with some content slipping out of view:

Screenshot 2024-04-04 alle 19 15 47

**Comment by dtonon** [comment]
@mikedilger 

> First, it doesn't respect dark mode. It is far too bright for me in dark mode.

It will be adapted.

> Second, can we make it subdued if you have nothing pending? It's not obvious to notice a '3' versus a '0' it should change colors or something to indicate visually that something needs to be addressed.

Sure. When there are no items to review, the counters should be deactivated/desaturated:

image

/cc @bu5hm4nn

**Pull request merged**
