### PR TITLE
Place "Advertise Relay List" next to title

### PR DESCRIPTION
**Pull request by bu5hm4nn**

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
IMAGE 2023-08-24 15:37:20

**Comment by bu5hm4nn** [comment]
@dtonon please review

**Comment by bu5hm4nn** [comment]
Tried to add Daniele as a reviewer but somehow don't have any such option still

**Comment by mikedilger** [comment]
I don't know how to do it.  I can't add @dtonon as a reviewer either.

**Comment by dtonon** [comment]
@bu5hm4nn I offered my suggestion here: https://github.com/mikedilger/gossip/pull/478#issuecomment-1694311283

**Comment by dtonon** [comment]
@bu5hm4nn I cannot run this branch with my unstable db:

> INFO src/filter.rs:30: No spam filter: No such file or directory (os error 2)
Error: Error { kind: General("Migration level 7 unknown: This client is older than your data."), file: None, line: None }

Can you rebase it?

However I think it is ok, we just need to right align the search input and the button.
I would also reword the button in "Advertise" to make it more compact, and put "Advertise the relay list (NIP-65)" as tooltip.

**Pull request merged**
