### PR TITLE
Feature/profiles UI restyle

### PR DESCRIPTION
**Pull request by bu5hm4nn**
Restyle according to #508

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
Still needs
- [ ] Button styling for dark mode
- [ ] A way to show relationship with a profile (following, muted, on list)

**Comment by dtonon** [comment]
@bu5hm4nn 

> Button styling for dark mode

For the primary button we also use the accent for the bg and white for the text.
For the secondary the row color for the bg and white for text/border.

> A way to show relationship with a profile (following, muted, on list)

Following => Accent color.

Muted => Danger color (we need to add it to the theme, in the current preview is #FF5E57).

On list => I would not use different colors (we would need to persist them and add an edit mode), maybe just a unique dark grey (light theme) and light grey (dark theme); and I would show it only if the user is not also followed.

**Comment by dtonon** [comment]
@bu5hm4nn restyling pushed.
I need your help on a detail: I updated the modal + qrcode to give it more padding, but I'm unable to move the X in the top right :)

Screenshot 2023-10-24 alle 18 39 50

**Comment by bu5hm4nn** [comment]
> @bu5hm4nn restyling pushed. I need your help on a detail: I updated the modal + qrcode to give it more padding, but I'm unable to move the X in the top right :)

I fixed it in #562

**Pull request merged**
