### PR TITLE
eliminate all forms of "p" tag duplication

### PR DESCRIPTION
**Pull request by fiatjaf**
and also self-tagging.

### CODE REVIEW

**Comment by mikedilger** [comment]
This is good, except that I wanted to be able to have the option to explicitly remove 'p' tags from the event we were replying to... when you don't really want them to be notified of your reply.   I know that breaks the standard, and maybe I shouldn't have been thinking of doing it.

**Comment by fiatjaf** [comment]
I don't think it breaks any standard. In my mind these decisions of notifying or not notifying or what tags to include were always open for clients to decide.

**Comment by fiatjaf** [comment]
In this PR I've changed `draft_tags` to only contain the immediate reply and then the tags being included from direct mentions because my next step would be to actually remove the tags related to mentions once the mentions themselves (`#[1]` etc) were removed from the text.

But to achieve this and also achieve what you want we may need to split `draft_tags` into `draft_tags_parent` and `draft_tags_mentions`.

**Review by mikedilger — APPROVED** [review]
I'll just merge this now, and then we can make more changes later.  There's no reason to keep what we have now on master as it dups tags and we can't remove people yet.

**Pull request merged**
