### PR TITLE
Give themes more options to influence formatting

### PR DESCRIPTION
**Pull request by bu5hm4nn**
I ran cargo fmt and cargo clippy ~but I don't know how to satisfy clippy (matching first and last entries with an index-less for-loop?)~.

### CODE REVIEW

**Comment by dtonon** [comment]
Can you describe the new available options? I see a is_first/is_last but testing the Roundy theme I cannot spot the difference :)

The refactoring changed to the padding top/left inner padding of the Default theme, can you recreate the original layout, please? Left: original, Right: this PR:

image

**Comment by mikedilger** [comment]
I like this work. More options are better. I'll wait until the padding changed issue is resolved to merge it.

**Comment by bu5hm4nn** [comment]
Interesting, the padding must have gotten lost in the merge I had to do from my stash (a lot changed including the creation of notes/mod).

is_first and last have meaning in threads, but I chose to only use it on the first post in a thread to round the top corners.

**Comment by bu5hm4nn** [comment]
@dtonon So the space change came from wrapping the post in a horizontal layout. There was a space of 4.0 being added which before was part of the vertical spacing, which now turned into a horizontal space.

I fixed it by removing the add_space call and used margin to adjust to the desired position. If you want spacing to a previous post you can also use a transparent border in feed_post_separator_stroke and adjust the width.

Does that work for you?

**Comment by dtonon** [comment]
@bu5hm4nn thank you for the details and fix, seems good!

**Pull request merged**
