### PR TITLE
Count all trailing newlines and trim them off. Then render them later…

### PR DESCRIPTION
**Pull request by bu5hm4nn**
… with `ui.end_row()`

### CODE REVIEW

**Review by mikedilger — COMMENTED** [review]
LinkFinder should not be giving us links that need trimming (line 22), did you find that it did?

This bug seems to be to be a bug in egui TextLayout.  If there are two newlines it shouldn't be indenting.  Hacking around this will probably cause more probems if egui fixes their bug.

But egui is slow as molassass to do anything anymore (I have an open issue with them on another text layout bug) so we might have to fix it for them on a fork.

**Comment by bu5hm4nn** [comment]
Shoot, line 22 is leftover from bug search. I'll correct that.

Yeah I believe it's a bug in egui. I believe we are using your fork of egui. Shall I make an effort to fix it in egui?

**Comment by mikedilger** [comment]
If you want to.  I think I trace it into the logic in this file `egui/crates/epaint/src/text/text_layout.rs`

**Comment by mikedilger** [comment]
I presume this one is no longer needed?

**Pull request closed without merging**
