### PR TITLE
Feature/fix tagging popup for compose at bottom

### PR DESCRIPTION
**Pull request by bu5hm4nn**

### CODE REVIEW

**Comment by dtonon** [comment]
@bu5hm4nn feedbacks:

- [ ] Remove the tooltip on the options (it is not so useful)
- [ ] Double the space from the options icons and "Cancel" (to avoid an unintended reset)
- [ ] Make the "Cancel" default color gray (it is not a main CTA)
- [ ] Make the "Send" button in the accent color (it is the main CTA)
- [ ] When clicking a button inside the popover, close it (it is rare that an user need to click 2 buttons in sequence)
- [ ] I would transform "Show raw preview" in a button
- [ ] Review the popover colors:
_Dark_: for background pick the same color used for the note dropdown, buttons with the accent color and white text, no border.
_Light_: for background pick the same color used for the note dropdown I'm beginning to believe that it's better not to use the accented color, too prominent), buttons white white and accent color text, no border. 

If not to comples:
- [ ] When the user clicks "Cancel" replace it with "Are you sure? [Yes reset the draft](url) - [No, keep it]()". The first link clear all and close the compose area, the second one revert to the initial state showing Cancel again.

**Comment by dtonon** [comment]
@bu5hm4nn can we update the bottom area when the raw mode is active, to make it obvious that it is not editable?

image

**Comment by bu5hm4nn** [comment]
Yes, however it still makes sense to send when in raw mode.

We could also do a "Preview" button like GitHub comments. Next to "Send".
It would be "Preview" -> "back to edit" or "Send"

**Comment by dtonon** [comment]
> however it still makes sense to send when in raw mode.

Oh right!

> We could also do a "Preview" button like GitHub comments. Next to "Send".
It would be "Preview" -> "back to edit" or "Send"

I would not over complicate, I think raw mode will not be used so often, the user knows that he need to go back to edit if want to review again the visual offtagged users before send.

**Comment by bu5hm4nn** [comment]
@dtonon I tried to apply all requested changes:
Screenshot 2023-12-15 at 12 23 38
Screenshot 2023-12-15 at 12 23 43

**Comment by dtonon** [comment]
@bu5hm4nn perfect!
The only thing that is missing is the double click for the cancel action.
Another details would be to use a gray background for the disabled button (we will standardize them asap).

**Pull request merged**
