### PR TITLE
Feature/relay list widget

### PR DESCRIPTION
**Pull request by bu5hm4nn**
I think we can merge this now and add new features and color fixes later. I made dark mode usable for now.

### CODE REVIEW

**Comment by mikedilger** [comment]
In Cargo.toml you should not use `branch = "master"` because that gives you too much power. You could change the code right before someone compiled what they thought they had just code-reviewed, and it will pick up the newest commit.  So change that to rev = "7041ed3f2f9b63b942936ba5ee172a1ef6940c0c" instead (I know it is a pain to keep these updated, but it is for a good security reason).

Now to some actual feedback.

When I'm looking at Active Relays, I'm seeing [R+I W+O D A] bits, but not the reason that relay is currently connected.  Check the unstable branch and notice how it fills these in.  Nobody is connected to 'advertise' but maybe for 'discovery' or 'config' or 'mentions'... which aren't really one of those bits.  It's a bit more detailed reason for the connection than those relay bits provide.

Also, with this new layout, I can't easily see the 16 relays I'm connected to on one screen because there isn't enough space, so I can't watch them all, I will always miss some off the screen, which feels like a loss to me.

Overall it looks and feels a lot better, and I'm impressed with the deep egui work. Must have been a pain.

**Comment by mikedilger** [comment]
Oh, and there is the "hide" button at the top, but do the relays have a hide still? I can't recall seeing it (not looking at the moment).

**Comment by dtonon** [comment]
If the coverage list is longer than the viewport it is not possibile to scroll it anymore:

Screenshot 2023-06-17 alle 17 38 09

Btw I think we should move it to his own section, as per my recent comment on the group:

> If the list is often populated I would move it in a separate view, as in my design, and maybe put a visual alert (ex. "!" or a small dot) near the menu label to signal that there is an unusual situation that could require a manual intervention.

And so add the "Pick again" button.

**Comment by dtonon** [comment]
@mikedilger check this new design: the connection reasons are back, this is the "compact mode"; using a toggle the user can show the relays stats. 

This sort of settings popup is really useful because can be used to collect a lot of small contextual preferences, keeping the main interface clear; for example we can move here the sort select if we evaluate that it is a low frequency tool. Of course can/should be used in other views.

Let me know if you like it.

Screenshot 2023-06-18 alle 22 25 52
Screenshot 2023-06-18 alle 22 26 19

**Comment by mikedilger** [comment]
Looks good.  I was imagining in the shower (where I do my best thinking) that the reasons "follows", "mentions", etc. could all be represented by icons, like follows could be that walking person, config could be a gear, augments could be a heart-zap combined together, etc.... if that saves space.

**Comment by dtonon** [comment]
You are right, some icons could make sense and save space for sure, even if the labels are maybe more clear/direct.
Now it seems we have max 5 reasons and I see that "mentions" is often duplicate:

image

What do the [ ] brackets mean?

**Comment by mikedilger** [comment]
I think the brackets mean it is an always-on subscription, reconnecting to re-establish the subscription as needed. Without brackets means it was just picked by the relay picker and it serves for the moment.

**Comment by dtonon** [comment]
Ok, but how this fit with the "mentions" example that is duplicated? A bug?
Do you think is it ok to use a color to distinguish the two, still keeping the temp connections to the right?

**Comment by mikedilger** [comment]
Reasons currently include:   discovery, config, mentions, follow, fetch-event, tmp-metadata, augments, posting, advertising, post-like, pull-contacts, pushing-contacts, write-metadata, reposting, read-thread and deleting.

Maybe icons isn't right.

**Comment by dtonon** [comment]
Some feedbacks / proposals.
Items marked with 📍 are in my opinion the priorities.

---

## Add a relay
- [ ] A1 📍 We should check if the host actually exist (DNS), otherwise refuse it. This helps to avoid misspelling.
- [ ] A2 📍 If a host is added without the protocol, let's assume "wss://".
- [ ] A3 - Some invalid hosts (ex. "wss://relay.damus.io." or "wss://.relay.damus.io") pass the check, could be solved by A1.
- [ ] A4 📍 The error message "That's not a valid relay URL" should be showed inside the modal and not in the sidebar.
- [ ] A5 - After adding a relay instead of filter it by name it should be placed on the top of the list in edit mode, because the user must personalize it.
- [ ] A6 📍 After adding & enabling a relay (read/write) it does not connect, no activity in the log, I have to restart gossip.

## Edit a relay
- [ ] E1 📍 When editing a relay the list refresh must be stopped.
- [ ] E2 📍 Light theme: when editing a relay the background of the other should be darker (ex. 50% opacity), like in the dark theme, to focus the edit area. Related to L5.
- [ ] E3 - The action "Remove from personal list" does not works.
- [ ] E4 - Force disconnect should be disabled (gray and without underline) if the relay is not connected.
- [ ] E5 - The action "Force disconnect" does not give any feedback, could be solved by E4.
- [ ] E6 - Make the tooltips less wide to improve readability.

## All relays lists
- [ ] L1 📍 Update compact/expand views as [proposed](https://github.com/mikedilger/gossip/pull/402#issuecomment-1596269521).
- [ ] L2 - Add a sort by name (a-z).
- [ ] L3 - Add a sort by add date (newer => older) and set it as a default.
- [ ] L4 - Show the host without the "wss://" protocol (could be added when switching to edit/details).
- [ ] L5 📍 Light theme: items background should be white.

## Active relays view
- [ ] R1 📍 The coverage list should be moved to another view; currently if it is taller that the viewport is not possibile to scroll it and the the actual relays.

I'm not able to check further because R1.

## My relays view
All good :)

## Know network view
- [ ] K1 📍 Add "Hide from the view" near "Force disconnect".

## Bootstrap a fresh profile
- [ ] B1 📍 Hide all the "Relays" menu block and show only the "Add relay" button.

## Cosmetics
- [ ] C1 - Revert light theme accent color to the original one.
- [ ] C2 - Review "Add relay" button colors/hover/spacing/font-size.
- [ ] C3 - Review "Close" button font-size.

---

Let me know!

**Comment by dtonon** [comment]
A detail of L6: _Show a bullet in front off the relay showing the status: green => connected, gray => disconnected; yellow => penalty box (hovering over the mouse shows the remaining time)._

Screenshot 2023-08-09 alle 01 07 26

The yellow bullet could change in relation to the penalty remaining time, ex:
yellow: < 120s
orange: > 120s && < 300s
red: > 300s

If possible I would add another select-filter on the top with:
\- All status
\- Connected
\- Disconnected
\- In penalty box

@mikedilger @bu5hm4nn any feedback?

**Comment by mikedilger** [comment]
The thing that hangs in my head about this is that I want to see all connected relays at a glance, not have to scroll through them.  I like that your last image @dtonon has only 1 line per relay.  I think I could get that.

All the things you are suggeting sound great to me. I'm very happy with you and @bu5hm4nn s work on this.

**Comment by bu5hm4nn** [comment]
> L3 - sort by add date
@mikedilger I don't think we store when the relay was added, do we?

**Comment by bu5hm4nn** [comment]
Regarding E2 and L5, currently disabled regions get tinted by egui, I just set all the backgrounds to `visuals.extreme_bg_color`, if there is a difference between dark mode and light mode, then we might want to investigate if we can fix it everywhere. Maybe we can have a chat on that @dtonon

**Comment by mikedilger** [comment]
Every time I want to make extensive code changes, this branch makes me hesitate. If I make extensive code changes it will make this branch harder to merge. But I can't wait 3 months to make extensive code changes. So I did the LMDB one, and I'm about to start on changing settings (app.settings will go away from the UI). I recommend merging in master from time to time and sorting out the differences. I can still merge it (with difficulties) and have on my local machine. After I make the settings changes, I fear merging will be very hard.

A strategy I've used in the past is to collapse a long branch into a single commit (rebase fixup all the way), keeping the original branch just in case to refer to, but using that single commit to see the full set of changes in one place.  Then I break up those changes into functional units and apply them as new commits onto wherever master is.  This also makes all the commits pretty and single-topic.  So that's an option.

Anyhow, I keep worrying about this so I thought I'd better say something.

**Comment by bu5hm4nn** [comment]
Yes, I absolutely get that. Unfortunately when I started work on this, Daniele didn't have time to thoroughly review. After he thoroughly reviewed, I didn't have time to go through his list.

Right now I am working on finishing up the remaining items for this list. I will then merge master. All should get done before the weekend.

**Comment by bu5hm4nn** [comment]
'unstable' branch is merged in.
@dtonon please review your list. Most items should be addressed, some are not. I would recommend we merge unless there are big bugs, and then address the remaining items in individual fix-merges.
@mikedilger I think the "files changed" view here on github is now quite managable for this branch.

**Comment by nbenaglia** [comment]
I think this PR solved the issue #450

**Comment by dtonon** [comment]
@bu5hm4nn I'm checking the current unstable and updated the checklist.

Notes about the updates:
E5 - Closing the modal is ok but would be nice to give a 5 secs delay before the reconnecting, so the user can see the gray icon; currently the reconnecting is immediate and the gray icon is visible < 1s

Notes about not updated:
A1 - Is it easily applicable? Otherwise we can postpone it, the formal checks are more important.
A* - Have these points been addressed somehow? I cannot activate the "That's not a valid relay URL" error message but the host formal check is not still working very well. 
E2 - I don't think is a priority anymore; we can review it when we will check how to manage the egui logic and incorporate it in our theme needs.

Added points:
E7

I have not finished the check, I will update the report in the next hours!

**Comment by dtonon** [comment]
For B1 I'm waiting #474 because I cannot test a new profile anymore.

**Comment by dtonon** [comment]
@mikedilger do you want the reasons to always be visible? I'm trying to find a tradeoff between a compact view and the richness of information. Icons, as you proposed time ago, are a solution. Otherwise we can move them in the "details" mode.

I see the reasons more like a advanced/debug information, am I completely wrong? :)

**Comment by dtonon** [comment]
The listing view optimization moved here: #466

**Comment by mikedilger** [comment]
Please test unstable and tick A6 if working now.

**Comment by dtonon** [comment]
@mikedilger since the PR has been merged the discussion has been moved here: https://github.com/mikedilger/gossip/issues/477
I will update you there.

**Pull request merged**
