### PR TITLE
Allow mentions/quotes to be made

### PR DESCRIPTION
**Pull request by fiatjaf**
(adding "mention" "e" tags along with a reference to them in `.content`).

does it just like the npub-parsing thing, now with note1 parsing.

also refactors some of the previous PR that added npub parsing and fixes a bug that caused mentions to not be recognized some times.

### CODE REVIEW

**Comment by mikedilger** [comment]
You sir have used `.flatten()` which I have never used. Fancy.

That quote icon is not rendering for me. Looks like a cube of tofu.  And the spacing looks weird.

There is a lot of console output that probably should be removed now.

**Comment by fiatjaf** [comment]
Should be good now.

> You sir have used `.flatten()` which I have never used. Fancy.

When are we going to get `.flatmap()` on Rust?

**Comment by fiatjaf** [comment]
I've also added `nprofile1` parsing from notes along with `npub1`, but the relay data contained in `nprofile1` links is being discarded because I couldn't find a function in the database module for storing that, which I think may be in your plans, so once that part is resolved we can use it when parsing notes too somehow.

**Comment by fiatjaf** [comment]
Should I be running this clippy thing? I don't know what that is.

**Comment by mikedilger** [comment]
https://doc.rust-lang.org/stable/core/iter/trait.Iterator.html#method.flat_map

**Comment by mikedilger** [comment]
Ok I'll look at nprofile later. I'm at work so I can only work on gossip while waiting for some computer to finish doing it's thing. At home I'll have more time.

I'd prefer if you ran `cargo clippy` and `cargo fmt`.  The first one suggests ways to simplify your code or make it more "idiomatic"

**Review by mikedilger — APPROVED** [review]

**Pull request merged**
